remote_theme: rampatra/photography 
logo: https://raw.githubusercontent.com/microsolco/microsolco.net/gh-pages/lp.png


plainwhite:
  name: Microsolco
  tagline: 33 giri e 1/3 al minuto
  date_format: "%b %-d, %Y"
  portfolio_image:      "lp.png"
  portfolio_image_dark: "lp.png"
  dark_mode: true

  social_links:
    twitter: microsolco
    github: microsolco


photography:
  # Base configs
  baseurl: ""
  image_fulls_loc: "/images/fulls"
  image_thumbs_loc: "/images/thumbs"

  # UI configs
  title: "Photography by me"
  subtitle: "See the world through my eyes!"
  author: "LP"
  header:
  title: "Photography"
  subtitle: "by me"
  footer:
  name: "Hey there, my name is LP"
  bio: "bio"
  github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
  web_design: "LP"
  #social_urls:
  #  facebook: "https://www.facebook.com/ramswaroop"
  #  twitter: "https://www.twitter.com/ram__patra"
  #  instagram: "https://www.instagram.com/ram_patra"
  #  dribbble: "https://dribbble.com/rampatra"
  #  linkedin: "https://in.linkedin.com/in/ram-patra"
  #  github: "https://www.github.com/rampatra"
