remote_theme: samarsault/plainwhite-jekyll
logo: https://raw.githubusercontent.com/microsolco/microsolco.net/gh-pages/lp.png


plainwhite:
  name: Microsolco
  tagline: 33 giri e 1/3 al minuto
  date_format: "%b %-d, %Y"
  portfolio_image:      "lp.png"
  portfolio_image_dark: "lp.png"

  social_links:
    twitter: microsolco
    github: microsolco
